# On Push:
#   This action will run tests on the Node project:
#     If tests pass: 
#       Deploy new website
#       Push new Docker image to DockerHub
name: On Push CI/CD 

on:
  push:
    branches: [main]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run build
        env:
          CI: false
      - name: Deploy to production
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push new Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pathfinding:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
